### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sngjuk** [sngjuk/meme-glossary#2]
- [ ]  dank query with probability option. (using similarity)
- [ ]  tf-idf scoring.
- [x] manual_labeler.py, keep original label while labeling.
- [ ] path string addition -> os.path.join() change.
- [ ] model.py del implementation
- [ ] embedding performance.
- [ ] packaging
- [ ] dockerfile
